import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    bg: {
      page: "color-bg-page",
      surface: "color-bg-surface",
      elevated: "color-bg-elevated",
      sunken: "color-bg-sunken",
      overlay: "color-bg-overlay",
    },
    text: {
      primary: "color-text-primary",
      secondary: "color-text-secondary",
      muted: "color-text-muted",
      disabled: "color-text-disabled",
      inverse: "color-text-inverse",
      onBrand: "color-text-on-brand",
    },
    border: {
      default: "color-border-default",
      strong: "color-border-strong",
      focus: "color-border-focus",
      error: "color-border-error",
    },
    brand: {
      default: "color-brand",
      hover: "color-brand-hover",
      active: "color-brand-active",
      subtle: "color-brand-subtle",
      text: "color-brand-text",
    },
    success: {
      default: "color-success",
      bg: "color-success-bg",
      text: "color-success-text",
    },
    warning: {
      default: "color-warning",
      bg: "color-warning-bg",
      text: "color-warning-text",
    },
    error: {
      default: "color-error",
      bg: "color-error-bg",
      text: "color-error-text",
    },
    info: {
      default: "color-info",
      bg: "color-info-bg",
      text: "color-info-text",
    },
  },
  font: {
    sans: "font-sans",
    mono: "font-mono",
    size: {
      xs: "font-size-xs",
      sm: "font-size-sm",
      base: "font-size-base",
      lg: "font-size-lg",
      xl: "font-size-xl",
      "2xl": "font-size-2xl",
      "3xl": "font-size-3xl",
      "4xl": "font-size-4xl",
      "5xl": "font-size-5xl",
    },
    weight: {
      normal: "font-weight-normal",
      medium: "font-weight-medium",
      semibold: "font-weight-semibold",
      bold: "font-weight-bold",
    },
    leading: {
      tight: "leading-tight",
      snug: "leading-snug",
      normal: "leading-normal",
      relaxed: "leading-relaxed",
    },
  },
  space: {
    "0": "space-0",
    "1": "space-1",
    "2": "space-2",
    "3": "space-3",
    "4": "space-4",
    "5": "space-5",
    "6": "space-6",
    "8": "space-8",
    "10": "space-10",
    "12": "space-12",
    "16": "space-16",
  },
  radius: {
    none: "radius-none",
    sm: "radius-sm",
    md: "radius-md",
    lg: "radius-lg",
    xl: "radius-xl",
    full: "radius-full",
  },
  shadow: {
    sm: "shadow-sm",
    md: "shadow-md",
    lg: "shadow-lg",
    xl: "shadow-xl",
    brand: "shadow-brand",
    none: "shadow-none",
  },
  duration: {
    instant: "duration-instant",
    fast: "duration-fast",
    base: "duration-base",
    deliberate: "duration-deliberate",
    slow: "duration-slow",
  },
  ease: {
    default: "ease-default",
    in: "ease-in",
    out: "ease-out",
    spring: "ease-spring",
  },
  size: {
    btnSm: "button-height-sm",
    btnMd: "button-height-md",
    btnLg: "button-height-lg",
    inputMd: "input-height-md",
    header: "header-height",
    sidebar: "sidebar-width",
    // dialogSm: "dialog-height-sm",
    // dialogMd: "dialog-height-md",
    // dialogLg: "dialog-height-lg",
  },
  zIndex: {
    dropdown: "z-index-dropdown",
    modal: "z-index-modal",
    popover: "z-index-popover",
    tooltip: "z-index-tooltip",
    overlay: "z-index-overlay",
  },
});
